// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mockOSApi.Data;

#nullable disable

namespace mockOSApi.v2.Migrations
{
    [DbContext(typeof(OSDbContext))]
    [Migration("20240423181820_ProcessAddedStuff")]
    partial class ProcessAddedStuff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("mockOSApi.Models.MockProcess", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Pid"));

                    b.Property<string>("Args")
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("ExitCode")
                        .HasColumnType("int");

                    b.Property<string>("FileDescriptors")
                        .HasColumnType("longtext");

                    b.Property<int>("Handle")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsService")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Pid");

                    b.ToTable("MockProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
