// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mockOSApi.Data;

#nullable disable

namespace mockOSApi.v2.Migrations
{
    [DbContext(typeof(OSDbContext))]
    [Migration("20240610114208_addedThreadsToProcess")]
    partial class addedThreadsToProcess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("mockOSApi.Models.MockProcess", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Pid"));

                    b.Property<string>("Args")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("ExecutionTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("ExitCode")
                        .HasColumnType("int");

                    b.Property<string>("FileDescriptors")
                        .HasColumnType("longtext");

                    b.Property<int>("Handle")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsService")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserUid")
                        .HasColumnType("int");

                    b.HasKey("Pid");

                    b.HasIndex("UserUid");

                    b.ToTable("MockProcesses");
                });

            modelBuilder.Entity("mockOSApi.Models.MockThread", b =>
                {
                    b.Property<int>("Tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Tid"));

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("ExitCode")
                        .HasColumnType("int");

                    b.Property<int>("Handle")
                        .HasColumnType("int");

                    b.Property<int>("MockProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("StackId")
                        .HasColumnType("int");

                    b.Property<string>("StartFunction")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Tid");

                    b.HasIndex("MockProcessId");

                    b.HasIndex("StackId");

                    b.ToTable("MockThreads");
                });

            modelBuilder.Entity("mockOSApi.Models.MockThreadStack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("Handle")
                        .HasColumnType("int");

                    b.Property<string>("Stack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MockThreadStacks");
                });

            modelBuilder.Entity("mockOSApi.Models.User", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Uid");

                    b.ToTable("User");
                });

            modelBuilder.Entity("mockOSApi.Models.MockProcess", b =>
                {
                    b.HasOne("mockOSApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("mockOSApi.Models.MockThread", b =>
                {
                    b.HasOne("mockOSApi.Models.MockProcess", "Parent")
                        .WithMany("Threads")
                        .HasForeignKey("MockProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mockOSApi.Models.MockThreadStack", "Stack")
                        .WithMany()
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("mockOSApi.Models.MockProcess", b =>
                {
                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
