// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mockOSApi.Data;

#nullable disable

namespace mockOSApi.v2.Migrations
{
    [DbContext(typeof(OSDbContext))]
    [Migration("20240423193149_ProcessAddedUser2")]
    partial class ProcessAddedUser2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("mockOSApi.Models.MockProcess", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Pid"));

                    b.Property<string>("Args")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("ExitCode")
                        .HasColumnType("int");

                    b.Property<string>("FileDescriptors")
                        .HasColumnType("longtext");

                    b.Property<int>("Handle")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsService")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("RunTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserUid")
                        .HasColumnType("int");

                    b.HasKey("Pid");

                    b.HasIndex("UserUid");

                    b.ToTable("MockProcesses");
                });

            modelBuilder.Entity("mockOSApi.Models.User", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Uid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("mockOSApi.Models.MockProcess", b =>
                {
                    b.HasOne("mockOSApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
